version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: some-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - some-network

volumes:
  redis-data:

networks:
  some-network:
    driver: bridge
